// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzX4H07aDSUw59xR0PF_WhVsg2RuF5_iI',
    appId: '1:754616473372:web:0aef2c55eaf6edcf3d8cd9',
    messagingSenderId: '754616473372',
    projectId: 'littlelounge-f2f31',
    authDomain: 'littlelounge-f2f31.firebaseapp.com',
    storageBucket: 'littlelounge-f2f31.appspot.com',
    measurementId: 'G-RLVR52TEXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWmpuhYw7QnHz5wVEIT3OFxCJ82ztBPQ',
    appId: '1:754616473372:android:41785da29c6685d43d8cd9',
    messagingSenderId: '754616473372',
    projectId: 'littlelounge-f2f31',
    storageBucket: 'littlelounge-f2f31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl774CwVsOT9zd-stpN_hAC6wxXXVjciI',
    appId: '1:754616473372:ios:e48a1dea8ee5e6413d8cd9',
    messagingSenderId: '754616473372',
    projectId: 'littlelounge-f2f31',
    storageBucket: 'littlelounge-f2f31.appspot.com',
    iosBundleId: 'com.example.littlelounge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzX4H07aDSUw59xR0PF_WhVsg2RuF5_iI',
    appId: '1:754616473372:web:de9cb1646ac4abce3d8cd9',
    messagingSenderId: '754616473372',
    projectId: 'littlelounge-f2f31',
    authDomain: 'littlelounge-f2f31.firebaseapp.com',
    storageBucket: 'littlelounge-f2f31.appspot.com',
    measurementId: 'G-R50NCBTB4W',
  );
}
